#!/bin/bash

echo "🔥 Firebase Configuration Helper"
echo "================================="
echo ""
echo "After creating your Firebase project, copy these values from Firebase Console:"
echo ""
echo "1. Go to: https://console.firebase.google.com"
echo "2. Select your project"
echo "3. Click Settings (⚙️) → Project settings"
echo "4. Scroll to 'Your apps' section"
echo "5. Copy the config values and update lib/firebase_options.dart"
echo ""
echo "Example values you need to replace:"
echo "  - apiKey: 'AIzaSyC...' (from Firebase config)"
echo "  - appId: '1:123456789:android:abc123...' (from Firebase config)"
echo "  - messagingSenderId: '123456789' (from Firebase config)"
echo "  - projectId: 'your-project-name' (from Firebase config)"
echo "  - storageBucket: 'your-project-name.appspot.com'"
echo ""
echo "📱 For Android, also place google-services.json in android/app/"
echo ""
echo "✅ After updating, your app will connect to Firebase properly!"
